default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: postal_development

test:
  <<: *default
  database: postal_test

production:
  <<: *default
  database: postal_production
  username: postal
  password: <%= ENV['POSTAL_DATABASE_PASSWORD'] %>
